### ISSUE TITLE
Implement edit function

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#100]
**Context**
Implement edit function to CLI in TS

**How to**

- [x] Implement edit function
- [x] Make sure to manage the deletion of files

**Comment by thomas-senechal** [comment]
Need to update https://github.com/massalabs/DeWeb/pull/112/files/28398d18437e4e76c6608a26d0508c0f2db5c3fb#diff-de0791a9424209b08e87c38d10537a3532a081a185459b4fc28d4595c3b0ac3aR14 with immutability and deweb version storage introduced here https://github.com/massalabs/DeWeb/pull/126/files#diff-3ebdaef67413baee44de673e3d6d885fe674d291758dbb9fb9857e27aa54e0f1R28
