### ISSUE TITLE
Add signing w/ secret key using CLI

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#102]
**Context**
As a user, I want to be able to sign operations automatically using my secret key so it's simpler than using external wallet.

**How to**

- [x]  Check the env for SECRET_KEY, if it exists, use it to "import" the wallet and sign operations
- [x]  Check the config file, if the secret key is specified, use it to "import" the wallet and sign operations
- [x]  If secret keys are specified in both the env and the config, the env is used

- [x] Import wallet from yaml file:
  - [x] As CLI arguments 
  - [x] From config file
      - [x] If specified in both env and config, argument overrides
      - [x] Make sure to handle specific cases like:
          - only wallet filepath is present in config, if password is present in arguments, ok, otherwise, error
          - only password is present in config, if wallet filepath is present in args, ok, otherwise, error

**Comment by pivilartisant** [comment]
```If specified in both env and config, argument overrides```  is this  incorrect: in my mind wallet import can only be made by two methods: arguments & config file, from env is exclude (except secret_key)
