### ISSUE TITLE
Error pages - add branding to error pages for Deweb

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#125]
**Objective**
Add branding to default error pages for a good user experience.

**How to**

- [ ] Existing error pages: 
404: https://testr.massa.network/
Not working: https://toto.massa.host/
Not available on this provider: https://toto.massa.network/
- [ ] Existing designs: https://www.figma.com/design/b2ppNK0ZMDXF0gNXyssmHx/Deweb?node-id=0-1&node-type=canvas&t=33okMSOY31ulS29R-0
- [ ] Use implemented logic used in landing page adding a random by default

**Comment by pivilartisant** [comment]
We need to check internally on some details
