### ISSUE TITLE
Stats # of websites

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#135]
**Context**
For the release of DeWeb on mainnet, we'd like to have a system to know the number of websites currently on chain. To do that, we will use the foundation API which reads directly the ledger to get data.

**How to**

- [ ] Ask rights to access the foundation api repository to Damir
- [ ] If needed, sync with Damir to see how he'd like this data to be accessed (new endpoint ? inside an existing one ?...)
- [ ] Create a counter that is incremented each time an address has the `\x07MASSA_DEWEB_VERSION` key
- [ ] Ensure the counter is working properly by:
  - 1. Get the number of websites from the API
  - 2. Deploy a website SC
  - 3. Get the number of websites from the API
  - 4. Check if the value is at least one than at step 1

**Comment by modship** [comment]
I didn't make a counter but I retrieved the list of addresses directly. 
(For the counter just take the size of the list)
