### ISSUE TITLE
(mainnet) migration of all ecosystems projects on DeWeb

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#141]
**Objective**
Migrate internal porjects on mainnet 

**How to**
- upload each of the project to mainnet see list here (https://github.com/massalabs/DeWeb/issues/141#issuecomment-2460035414)
- add redirection to .network for all our .massa.net (centralized) domains when applicable (vesting, mns, explorer)
- communicate on our ecosystem migration (commitment to decentralization)

**Comment by pivilartisant** [comment]
- [ ] create an internal list of these link

**Comment by pivilartisant** [comment]
landing page MS
    bridge FE
    explorer FE
    syntra
    massa.net
    massa.foundation
    mns
    vesting
    docs

**Comment by SlnPons** [comment]
* Who we'll pay the fees?
* How we'll do that exactly?

**Comment by pivilartisant** [comment]
> * Who we'll pay the fees?
> 
>     * How we'll do that exactly?

also migrating once is good, but if it's better if we add github action flows to update the builds at each merge

**Comment by pivilartisant** [comment]
define process to add to massa provider allowlist

**Comment by SlnPons** [comment]
> > * Who we'll pay the fees?
> >   
> >   * How we'll do that exactly?
> 
> also migrating once is good, but if it's better if we add github action flows to update the builds at each merge

What was the conclusion when we discuss this point? I can't remember

**Comment by SlnPons** [comment]
> define process to add to massa provider allowlist

@thomas-senechal could you specify (again) how the allowlist will work in this 1st phase please? 
Because indeed, I think we should describe how it works on the doc (for our ecosystem but also for partners). wdyt?

**Comment by pivilartisant** [comment]
> > > * Who we'll pay the fees?
> > >   
> > >   * How we'll do that exactly?
> > 
> > 
> > also migrating once is good, but if it's better if we add github action flows to update the builds at each merge
> 
> What was the conclusion when we discuss this point? I can't remember

Should appear in milestone 3 roadmap as added feature

**Comment by thomas-senechal** [comment]
> > define process to add to massa provider allowlist
> 
> @thomas-senechal could you specify (again) how the allowlist will work in this 1st phase please? Because indeed, I think we should describe how it works on the doc (for our ecosystem but also for partners). wdyt?

Are the explainations here enough ? 🤔 
https://docs.massa.net/docs/deweb/local-server-config/server-config#configuration-fields

**Comment by pivilartisant** [comment]
![Image](https://github.com/user-attachments/assets/e4d7fd98-daf7-43c6-b506-df963707a199)


![Image](https://github.com/user-attachments/assets/a2c3cfa9-95ce-4b73-9124-161f7c12a45b)

**Comment by damip** [comment]
It would be important I think to have a CI system to automatically redeploy on buildnet (eg. to avoid having an older version of the docs in there)

**Comment by pivilartisant** [comment]
https://docs.google.com/spreadsheets/d/1C4cQg2DLYUWPXCItA9dsWZ35WePMPNBi6a75R6OcfTk/edit?gid=0#gid=0
