### ISSUE TITLE
Implement CLI upload flow in front end

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#154]
**Objective**
Develop the FE for the upload flow to enable users to sign and upload a website on chain.

**How to**

**Comment by pivilartisant** [comment]
> @pivilartisant
> 
> You can use the [UploadManager](https://github.com/massalabs/DeWeb/blob/main/cli/src/lib/uploadManager.ts) for the chunk batches upload. It takes a callback that is called when an operation is updated. You have an example of [the UploadManager in use here](https://github.com/massalabs/DeWeb/blob/main/cli/src/tasks/upload.ts#L40C1-L69C9)
> 
> I highly recommand you to check the cli upload flow to reuse as much as possible for the front end

I'm wondering for this first build, should i setup a wallet connection or generate a key pair with a yaml file ? i'm guessing droppping the yaml in the website is not the best in terms of security ?
