### ISSUE TITLE
Retrieve websites list - Dev appropriate SC

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#178]
**Context**
We need a way to store websites owned by an address somewhere. ATM, we can only know who owns a website, but not the opposite way, the websites owned by an address. A solution to this issue is to store the deployed SC address in the address that performed the deployment datastore. This would then allow people to view a list of the websites they own.

This could be made in a generic way to allow people to create a kind of "contact list" so people could store any address they want, with at least a "name" matching each address to make it easier to find a specific address.

This could become a standard to store data in an address datastore.

**How to**

- [ ] Decide which info to store/how to store data
- [ ] Decide which feature we need (add, delete, edit?)
- [ ] Init the SC
- [ ] Develop the SC accordingly to what was previously decided

**Comment by SlnPons** [comment]
For the 2 first points, here are my point of view: 
* which info: in the deweb context only store website name + SC address owned by the data store address. 
Note: it would be good to be able to use this `website name` for other things such as the index / search etc... to avoid having multiple sources of the same info.

* how to store it: idk

* Which feature / function to add: I would say CRUD (create, read, update, delete)

**Comment by pivilartisant** [comment]
seems to be the same as :https://github.com/massalabs/DeWeb/issues/181

**Comment by thomas-senechal** [comment]
Closing as it's the same as #181 which is done
