### ISSUE TITLE
Upload & test Liquity front-end on Buildnet

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#24]
**Objective**
To retrieve & deploy front-end on buildnet to test that everything is working well

**How to**

- [ ] Fork & build front-end
- [ ] Discuss with Designer if we want to custom things on the FE
- [ ] Deploy front-end 
- [ ] Upload front-end on Massa 
- [ ] Test that everything is working well (end-to-end) - if you don't know how to, please ask other devs in Massa (ex: Pierre, Damir...)

**Comment by pivilartisant** [comment]
How to be on liquity front-ends website: https://github.com/liquity/frontend-registry?tab=readme-ov-file

**Comment by pivilartisant** [comment]
how to develop liquity front end: https://github.com/liquity/dev?tab=readme-ov-file#development

**Comment by pivilartisant** [comment]
We're waiting on design customisation

**Comment by pivilartisant** [comment]
0x5fcFBC6681Db668f133e1E741045CEAf71d3fdfF is the registered address as frontend liquity tag

**Comment by pivilartisant** [comment]
We are waiting on someone to test it
