### ISSUE TITLE
Define the exact formula to calculate the deployment cost

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/DeWeb#30]
**Context:** 
Users might want an estimation of the cost of uploading their website. Defining the formula allowing to calculate the cost would allow users to have a rough estimation without having to deploy a website on buildnet. This could also be useful for marketing and communication.

**Objective:** 
To define the exact formula to calculate the overall cost to deploy one website.

**How to:** 
- [x] List all the cost to take into consideration. See below some points already identified: 
- [x] See storage cost formula in massa docs : https://docs.massa.net/docs/learn/storage-costs
- [x] Add the deployment fees 
- [x] Add the # of chunk and its cost 
- [x] Confirm the formula by:
  - [x] uploading websites of differents sizes on DeWeb
  - [x] multiple times: change the chunk size to a random value, and upload a website on DeWeb

**Comment by thomas-senechal** [comment]
Should be something like: 
var CHUNK_SIZE=64_000 (by default)
var WEBSITE_SIZE=1Mo (1_000_000 bytes) 
var NBR_CHUNKS=WEBSITE_SIZE/CHUNK_SIZE+1
const DEPLOY_PRICE (should always be the same as we always set the owner address, and creation timestamp)
var MINIMAL_FEES (depends on the node config)
const BYTE_STORAGE_COST=~0.0001 MAS

with those values, the formula should be something like: 
`f(x)=DEPLOY_PRICE+MINIMAL_FEES+NBR_CHUNKS*MINIMAL_FEES+WEBSITE_SIZE*STORAGE_COST`

This lacks the key storage cost and probably other stuff
And some values might not be 100% accurate. please make sure to check the documentation to use the appropriate formulas

**Comment by thomas-senechal** [comment]
# Deploy
website storer sc: 17719 bytes

Owner key is `OWNER`, 5 bytes => Address is up to 64 bytes => 5+64
FIRST_CREATION_DATE key is a `u8`, 1 byte, value is a `u64`, 8 bytes => 1+8

`0.001+0.0001*17719+0.0001*((4+1+8)+(4+5+64))`

So, `1.77815 MAS` of SC storage cost. We can add the minimal fees of `0.01 MAS` and we end up with `1.78815 MAS`

# Upload

First chunk we include:
LAST_UPDATE_TIMESTAMP creation: key is a `u8`, 1 byte, value is a `u64`, 8 bytes => 1+8
NB_CHUNKS creation: key is a `u8`, 1 byte, value is a `i32`, 4 bytes => 1+4

`0.0001*((4+1+8)+(4+5+64))` = `0.0086 MAS`

Each chunk requires a key corresponding to the chunk id and the value. 
The key is a `i32`, 4 bytes, value is a byte array, so, the length of the byte array => 4+`ToStoreLength`

`0.0001*(4+4+ToStoreLength)`

For example with a 9094 bytes website in one chunk:

`0.0001*(4+4+9094)` 

`0.9102 MAS` of chunk storage, add the `0.0086` for the first chunk storage => `0.9188`

If we have a limit of 2000 bytes per chunks, we end up with 5 chunks, that means we have 4 chunks of 2000 bytes and one of 1094 bytes.
So, the 4 full chunks will cost `0,2008` each, and the last chunk will cost `0.2002`. We add the additional cost of the first chunk, and we get `1.012 MAS`.

For each chunk, we need to add the minimal fees, which are `0.01 MAS`, so for the first example with a single chunk, we would end up with `0.9288 MAS`, and for the second one with 5 chunks, `1.062 MAS`

**Comment by thomas-senechal** [comment]
To confirm the estimation, I uploaded a website of 9094 bytes in one chunk,  and I have: 
Deploy cost: `1.8459 MAS`
Upload cost: `0.9224 MAS`
Total cost:     `2.7683 MAS`

For the deploy cost, the estimation gave `1.78815 MAS`, so, `0,06775` left for gas

For the upload cost, the estimation gave `0.9288 MAS`, so ⚠️ `-0,0064` left for gas ⚠️ 

The total estimation was `2,71695 MAS`

**Comment by thomas-senechal** [comment]
To confirm the estimation for the example with multiple chunks, I uploaded a website of 9094 bytes with a limit of 2000 bytes per chunks and I got: 
Deploy cost: `1.7904 MAS`
Upload cost: `0.9656 MAS`
Total cost:     `2.7560 MAS`

Deploy cost estimation is always the same (expect if we change the address but since I used the same, same result)

Upload cost estimation was `0.9656 MAS`, so we are good

Total cost is the same, so for now, we are all good.

**Comment by thomas-senechal** [comment]
### 1. **Deploy Cost Formula**
$$
Cost_{Deploy} = 0.001 + 0.0001 \times BytecodeSize + 0.0001 \times (4 + 5 + 64) + 0.0001 \times (4 + 1 + 8) + 0.01
$$

Where:
- \( BytecodeSize \): Size of the smart contract in bytes.
- \( (4 + 5 + 64) \): Represents owner address storage.
- \( (4 + 1 + 8) \): Represents the creation timestamp (1-byte key and 8-byte value).
- \( 0.01 \): Minimal fees.

### Example with **Website Storer SC: 17,719 bytes**
$$
Cost_{Deploy} = 0.001 + 0.0001 \times 17719 + 0.0001 \times (4 + 5 + 64) + 0.0001 \times (4 + 1 + 8) + 0.01
$$

Breaking it down:
- \( 0.001 + 0.0001 \times 17719 = 1.7719 \)
- \( 0.0001 \times (4 + 5 + 64) = 0.0073 \)
- \( 0.0001 \times (4 + 1 + 8) = 0.0013 \)
- Minimal fees = 0.01

So,

$$
Cost_{Deploy} = 1.7719 + 0.0073 + 0.0013 + 0.01 = 1.7915 \ MAS
$$

---

### 2. **Upload Cost Formula**

$$
Cost_{Upload} = 0.0001 \times \left((4 + 1 + 8) + (4 + 1 + 4)\right) + \sum_j \left(0.0001 \times (4 + 4 + ChunkSize_j)\right) + 0.01 \times \text{Number of Chunks}
$$

Where:
- \( (4 + 1 + 8) \) and \( (4 + 1 + 4) \): Represents `LAST_UPDATE_TIMESTAMP` and `NB_CHUNKS`.
- \( ChunkSize_j \): Size of each chunk in bytes.
- \( 0.01 \times \text{Number of Chunks} \): Minimal fees for each chunk.

---

### Example 1: **Website with 1 Chunk (9,094 bytes)**

$$
Cost_{Upload} = 0.0001 \times ((4 + 1 + 8) + (4 + 1 + 4)) + 0.0001 \times (4 + 4 + 9094) + 0.01 \times 1
$$

1. **One-time cost**: \( 0.0022 \ MAS \)
2. **Single chunk storage**: 

  $$
  0.0001 \times (4 + 4 + 9094) = 0.9102 \ MAS
  $$

3. **Minimal fee**: \( 0.01 \times 1 = 0.01 \ MAS \)

Total:

$$
Cost_{Upload} = 0.0022 + 0.9102 + 0.01 = 0.9224 \ MAS
$$

---

### Example 2: **Website with 286,968 bytes (5 Chunks, chunk size 64,000 bytes)**

For 5 chunks (4 full chunks at 64,000 bytes each, and 1 last chunk at 30,968 bytes):

$$
Cost_{Upload} = 0.0001 \times ((4 + 1 + 8) + (4 + 1 + 4)) + 4 \times 0.0001 \times (4 + 4 + 64000) + 0.0001 \times (4 + 4 + 30968) + 0.01 \times 5
$$

1. **One-time cost**: \( 0.0022 \ MAS \)
2. **For the 4 full chunks (64,000 bytes each)**:

  $$
  0.0001 \times (4 + 4 + 64000) = 6.4008 \ MAS \quad (\text{for each chunk})
  $$

  $$
  4 \times 6.4008 = 25.6032 \ MAS
  $$

3. **For the last chunk (30,968 bytes)**:

  $$
  0.0001 \times (4 + 4 + 30968) = 3.0976\ MAS
  $$

4. **Minimal fees**: \( 0.01 \times 5 = 0.05\ MAS \)

Total:

$$
Cost_{Upload} = 0.0022 + 25.6032 + 3.0976 + 0.05 = 28.753\ MAS
$$

**Comment by thomas-senechal** [comment]
Example 2 estimation is right.

**Comment by thomas-senechal** [comment]
### **Total Storage Cost Formula for a Website**

The total storage cost consists of two parts: **Deploy Cost** and **Upload Cost**.

#### **Full Formula:**
$$
Cost_{Total} = \left( 0.001 + 0.0001 \times BytecodeSize + 0.0001 \times (4 + 5 + 64) + 0.0001 \times (4 + 1 + 8) + 0.01 \right) + \left( 0.0001 \times \left( (4 + 1 + 8) + (4 + 1 + 4) \right) + \sum_{j=1}^{n} \left( 0.0001 \times (4 + 4 + ChunkSize_j) \right) + 0.01 \times n \right)
$$

Where:
- \( BytecodeSize \): Size of the smart contract in bytes.
- \( n \): Number of chunks.
- \( ChunkSize_j \): Size of each chunk in bytes.
- The first part represents the **Deploy Cost**, which includes the storage of the bytecode, owner address, and creation timestamp.
- The second part represents the **Upload Cost**, including the one-time cost for `LAST_UPDATE_TIMESTAMP` and `NB_CHUNKS`, plus the storage cost of each chunk, and minimal fees.
