### ISSUE TITLE
Announce Massa ecosystem projects on DeWEB

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#32]
To sync w/ Maria to prep' and announce correctly: 
- [ ] Sync w/ the team to validate all projects are on-chain
- [ ] Organise the mkt around massa ecosystem onboarding on DeWeb
  * Insist on the fact that you need feedback on what they need - give them a due date to come back to you

**Comment by pivilartisant** [comment]
waiting : https://github.com/orgs/massalabs/projects/17/views/2?pane=issue&itemId=72554582

**Comment by SlnPons** [comment]
Let's consider it done then!! Well done guys :)
@pivi don't hesitate to reopen it if needed.
