### ISSUE TITLE
Unlock DeWeb to Ecosystem projects

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#53]
- [x] Make repo public
- [x] Check ReadMe and improve it if needed
- [x] Contact projects - define a due date
- [ ] Organise meetings to get feedback

**Comment by pivilartisant** [comment]
Were going to launch meeting beginning of next week with the objective of closing by the 21st

**Comment by pivilartisant** [comment]
We had written feedbacks, I was in regular contact with different ecosystem builders through telegram & discord. 

Formal meeting not necessary. 

See notion: https://www.notion.so/massa-innoteam/Beta-launch-feedback-e9118f0130514c61ac7890f5a2ae6f6d?pvs=4
