### ISSUE TITLE
Improve CLI signer flow 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/DeWeb#74]
- [ ]  enable singing operation wuith any massa wallet
- [ ]  check that massastation is open before sending operation in cli

**Comment by SlnPons** [comment]
Not sure to understand what we refer to when we say "flexibility". To be discussed with @pivilartisant :)

**Comment by pivilartisant** [comment]
> Not sure to understand what we refer to when we say "flexibility". To be discussed with @pivilartisant :)

updated

**Comment by SlnPons** [comment]
Not relevant anymore.
