### ISSUE TITLE
Research: popular open-source DeFI protocol for DeWeb

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/DeWeb#79]
liquity is not the most popular
: https://defillama.com/forks 
<img width="620" alt="Screenshot 2024-08-20 at 12 22 20" src="https://github.com/user-attachments/assets/0e6b091b-7026-4eed-8b11-b1254d034cc3">

-> time box research (2h) to see what popular AAVE DeFI protocols would could fork and upload. 
-> objective is to use it as a funnel for DeWeb

if outcome of research is positive -> we upload test on buildnet || outcome is negative we maintain liquity front-strategy

**Comment by SlnPons** [comment]
@pivilartisant what do you want to do about this issue? Are you going to address it or Daniel is on it?

**Comment by pivilartisant** [comment]
> @pivilartisant what do you want to do about this issue? Are you going to address it or Daniel is on it?

outcome of research == aave front end is on chain on beta, need follow up issue to test interface during milestone 2
