### ISSUE TITLE
Create FAQ 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/DeWeb#82]
- Hosted on landing page or docs

**Comment by SlnPons** [comment]
@pivilartisant let's list the main questions that are coming up during the AMA next week in this issue to prep' the FAQ for the general doc.

**Comment by pivilartisant** [comment]
M from foundation is going to prepare list

**Comment by pivilartisant** [comment]
@SlnPons we should follow up on this next sprint and think of some integration with the landing page

**Comment by SlnPons** [comment]
> [@SlnPons](https://github.com/SlnPons) https://www.notion.so/massa-innoteam/FAQ-b5e909cb5a464df495b73385ccd046d1?pvs=4 can u review this ?

done, nice work. I just added a couple of questions :)
