### ISSUE TITLE
Prepare discussions about website storer v2

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#88]
- [x] Write a first message to explain what we want for:
  - [x] Immutability
  - [x] new storing logic
- [x] List people that would be relevant to discuss those subjects
- ~~ Setup meetings to discuss the ideas on both subjects~~ 
  - ~~ 1 meeting for Immutability~~
  - ~~ 1 meeting for New storing logic~~
- [x] Write a recap for both meetings
- [x] Decide what we will do for the WSv2 and write it in the recap

**Comment by thomas-senechal** [comment]
Recap is on the forum, [here](https://forum.massa.community/t/community-feedback-proposal-for-improving-website-storage-on-deweb/82/10?u=anack)
