### ISSUE TITLE
Registries v1

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/DeWeb#95]
**Objective:** 
For the release of DeWeb on mainnet, we need a way to list providers and websites, so users can access those easily

**How to**
- [x] Find how to ***simply*** store websites and providers
  - [x] The list of websites must be fetchable so a website can display them
  - [x] People must be able to ask for their website/provider to be added to the list
  - [x] Providers and Websites must NOT be in the same list
- [x] Implement the registry for providers 
- [x] Implement the registry for websites
- [x] Update the doc to enable people to do it

**Tech**
For providers, we need the url of the provider, ways to contact the owner, a small description of their website access policy (block/allow lists, what they filter ? only their websites ? only massa "officials" website ?...)

For websites, we need the `.massa` domain name, ways to contact the owner, a small description of what's on the website

**Comment by thomas-senechal** [comment]
Providers list will be there: https://github.com/massalabs/Deweb-Providers
Main thing that is missing a clean readme explaining how this work and how to add a provider to the list

**Comment by thomas-senechal** [comment]
Doc PR: https://github.com/massalabs/docs/pull/375

**Comment by thomas-senechal** [comment]
Waiting for merge

> Doc PR: [massalabs/docs#375](https://github.com/massalabs/docs/pull/375)
